apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-analytics-api
  namespace: video-analytics
  labels:
    app: video-analytics
    component: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-analytics
      component: analytics-api
  template:
    metadata:
      labels:
        app: video-analytics
        component: analytics-api
    spec:
      serviceAccountName: app-sa
      containers:
        - name: va-analytics-api
          image: 801867402650.dkr.ecr.us-east-1.amazonaws.com/analytics-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "video_db"
            - name: DB_USER
              value: "enpm818r_master_db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
