apiVersion: v1
kind: Service
metadata:
  name: va-frontend-svc
  namespace: video-analytics
  labels:
    app: video-analytics
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: video-analytics
    component: frontend
  ports:
    - name: http
      port: 80          # what Ingress / other services see
      targetPort: 8080  # container port


