apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-analytics-ingress-backend
  namespace: video-analytics
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # --- ADD THIS LINE ---
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
    - http:
        paths:
          - path: /api/upload(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: va-uploader-svc
                port:
                  number: 80
          - path: /api/analytics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: va-analytics-svc
                port:
                  number: 80
