apiVersion: apps/v1
kind: Deployment
metadata:
  name: va-processor
  namespace: video-analytics
  labels:
    app: video-analytics
    component: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-analytics
      component: processor
  template:
    metadata:
      labels:
        app: video-analytics
        component: processor
    spec:
      serviceAccountName: app-sa
      containers:
        - name: va-processor
          image: 801867402650.dkr.ecr.us-east-1.amazonaws.com/processor-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET_NAME
              value: "va-video-assets-dev-801867402650"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "video_db"
            - name: DB_USER
              value: "enpm818r_master_db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: AWS_SECRET_ACCESS_KEY
