apiVersion: v1
kind: Service
metadata:
  name: va-processor-svc
  namespace: video-analytics
  labels:
    app: video-analytics
    component: processor
spec:
  type: ClusterIP
  selector:
    app: video-analytics
    component: processor
  ports:
    - name: http
      port: 80
      targetPort: 8082
